name: Deploy Infrastructure

on:
  push:
    branches:
      - main

jobs:

  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate Docker Compose
        run: docker compose config

  deploy:
    needs: validate

    runs-on: ubuntu-latest

    steps:
      - name: Deploy Infrastructure
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HETZNER_HOST }}
          username: ${{ secrets.HETZNER_USER }}
          key: ${{ secrets.HETZNER_SSH_KEY }}
          script: |
            cd /opt/ecommerce-platform

            git pull

            docker compose up -d

            docker compose ps
